default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: password

development:
  <<: *default
  database: p2j_development

test:
  <<: *default
  database: p2j_test

production:
  <<: *default
  database: p2j_production
  username: p2j
  password: <%= ENV['P2J_DATABASE_PASSWORD'] %>
